### PR TITLE
add common exclusions for jetty developers

### PR DESCRIPTION
**Pull request by jmcc0nn3ll**
as per title

### CODE REVIEW

**Comment by mojavelinux** [comment]
I still would prefer all paths to be rooted. That ensures that the exclusions only match in expected places and not any depth. A rooted path is one that begins with `/`. The `/` references the root of the git repository (not an absolute path on the filesystem).

> If there is a separator at the beginning of the pattern, then the pattern is relative to the directory level of the particular .gitignore file itself. 

See https://git-scm.com/docs/gitignore#_pattern_format

**Comment by mojavelinux** [comment]
The following entry is a good case of when you want an unrooted path:

```
.DS_Store/
```

(note the trailing slash, though)

That's because this folder can (and likely will) occur anywhere.

**Comment by joakime** [comment]
Do we have a sane `.gitattributes` too?

**Comment by mojavelinux** [comment]
Here's what I tend to use for .gitattributes (with more diff settings if they apply for the project)

```
* text=auto eol=lf
*.css diff=css
```

**Pull request closed without merging**
