### PR TITLE
initial support for blog cards

### PR DESCRIPTION
**Pull request by jmcc0nn3ll**
Adds support for blog cards for the front page. Colors are temporary but seem flexible enough for what we want to do overall.

### CODE REVIEW

**Comment by mojavelinux** [comment]
Note that the UI project is configured to use ES5, which means no `let`, `const`, multiline strings, or stabby functions. We can look to migrate the build to allowing ES6, but it's just not set up that way at the moment (because it inherits from the default UI, which has yet to make that transition).

We may want to consider splitting the CSS (and maybe even the JS) for home area off from that used by the rest of the site. For example, home.css loaded after site.css. However, that could be a premature optimization. I just wanted to mention that it is possible.

**Comment by mojavelinux** [comment]
It would be good to add a preview page in the UI project so that this can be tested without building the whole site.

**Comment by jmcc0nn3ll** [comment]
Can you send my pointer to that?

**Comment by mojavelinux** [comment]
I have updated the PR to make this a more seamless integration. Here are the key changes:

* Add a feed block macro using an Asciidoctor extension
   * this macro will output the insertion slot with an optional section wrapper, then it will mark the page as having at least one feed
* Use a Handlebars template to supply the HTML template for a card
* Simplify the HTML structure and CSS for a card entry
* Move the supporting JavaScript (behavior) to a dedicated file and only load on pages that have at least one feed
* Refactor the supporting JavaScript (behavior)
* Add the feed integration to the UI preview for testing

The appearance of the cards could still use work. I did not really fiddle with the design.

**Comment by mojavelinux** [comment]
In the future, can you please submit PRs from a fork. Making branches in the upstream makes it messy.

**Comment by jmcc0nn3ll** [comment]
Sure, I'll do that, though not sure what I'll do beyond content for the time being.

thanks!

**Pull request merged**
