### PR TITLE
initial setup of website project

### PR DESCRIPTION
**Pull request by mojavelinux**
* import default Antora UI without docs starting from https://gitlab.com/antora/antora-ui-default/-/commit/91de243e4cd1d84effe43af31c1e01e7231ba568
* update project metadata, upgrade dependencies, and format source
* qualify stdlib requires; save path as ospath const
* replace String#substr with String#slice and configure lint rule to enforce
* add release process for UI
* add jetty logo; move search to nav end; mock up topbar nav
* add barebones home component
* add barebones contribution-guide component
* add Antora playbook with initial set of content sources
* add GitHub Actions workflow to build and publish site

### CODE REVIEW

**Comment by jmcc0nn3ll** [comment]
spiffy!

**Comment by mojavelinux** [comment]
We just need to get the UI release process to work now so we can switch over to the UI bundle from this project.

Can you create a personal access token for webtide that has the "repo" scope (no other scopes needed), then navigate to https://github.com/webtide/jetty.website/settings/secrets/actions and create a repository secret named `RELEASE_TOKEN` and paste in that value? That will allow the script to create tags and releases via the REST API. After that, I'll kick off the UI release again and switch to it when it's up.

**Comment by jmcc0nn3ll** [comment]
done....I think.

It needed to be a classic token right?

--
Jesse McConnell - ***@***.***> - CEO
http://webtide.com - advice, and support for jetty and cometd

**Comment by mojavelinux** [comment]
For now, yes, a classic token. I'm sure there's a way to use the new token, but I don't yet have experience with it.

**Pull request merged**
